//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trails
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotesEntities6 : DbContext
    {
        public NotesEntities6()
            : base("name=NotesEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<NoteCategories> NoteCategories { get; set; }
        public virtual DbSet<NoteTypes> NoteTypes { get; set; }
        public virtual DbSet<ReferenceData> ReferenceData { get; set; }
        public virtual DbSet<SellerNotes> SellerNotes { get; set; }
        public virtual DbSet<SellerNotesAttachements> SellerNotesAttachements { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
